apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-prometheus
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: prometheus
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.path=/prometheus"
        ports:
          - containerPort: {{ .Values.service.port }}
        volumeMounts:
          - name: config-volume
            mountPath: /etc/prometheus
          - name: data-volume
            mountPath: /prometheus
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-prometheus-config
        - name: data-volume
          emptyDir: {}
