replicaCount: 1

image:
  repository: ghcr.io/vincentdevopsresearch/skyworlditpp/itppui
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources:
  requests:
    memory: "1.5G"
    cpu: "250m"
  limits:
    memory: "2G"
    cpu: "500m"

imagePullSecrets:
  - name: ghcr-secret
