apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: sql-server
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: ACCEPT_EULA
          value: "{{ .Values.env.ACCEPT_EULA }}"
        - name: SA_PASSWORD
          value: "{{ .Values.env.SA_PASSWORD }}"
        volumeMounts:
        - mountPath: {{ .Values.persistence.mountPath }}
          name: mssql-data
      volumes:
      {{- if .Values.persistence.enabled }}
      - name: mssql-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc
      {{- else }}
      - name: mssql-data
        emptyDir: {}
      {{- end }}
