apiVersion: batch/v1
kind: CronJob
metadata:
  name: forecastingservice
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: forecastingservice
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: IfNotPresent
              env:
                - name: MONITORING_DB_CONNECTION_STRING
                  valueFrom:
                    secretKeyRef:
                      name: "{{ .Values.env.MONITORING_DB_CONNECTION_STRING.secretName }}"
                      key: "{{ .Values.env.MONITORING_DB_CONNECTION_STRING.secretKey }}"
                - name: PREDICTION_API_URL
                  valueFrom:
                    secretKeyRef:
                      name: "{{ .Values.env.PREDICTION_API_URL.secretName }}"
                      key: "{{ .Values.env.PREDICTION_API_URL.secretKey }}"
          restartPolicy: OnFailure
          imagePullSecrets:
            {{- if .Values.imagePullSecrets }}
            {{- toYaml .Values.imagePullSecrets | nindent 12 }}
            {{- end }}
