replicaCount: 1

image:
  repository: mcr.microsoft.com/mssql/server
  tag: 2022-latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 1433
  nodePort: 30001

persistence:
  enabled: true
  size: 5Gi
  storageClass: manual
  accessModes:
    - ReadWriteOnce
  mountPath: /var/opt/mssql

nodeSelector:
  database-storage: "true"

env:
  ACCEPT_EULA: "Y"
  SA_PASSWORD: "54879wMssql"
