---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
  - port: {{ .Values.service.amqp.port }}
    targetPort: 5672
    name: amqp
  - port: {{ .Values.service.management.port }}
    targetPort: 15672
    name: management
  - port: {{ .Values.service.prometheus.port }}
    targetPort: 15692
    name: prometheus
  selector:
    app: rabbitmq
  type: {{ .Values.service.type }}
