apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-ingress-controller
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "configmaps", "events", "secrets"]
    verbs: ["get", "list", "watch", "create", "patch", "update"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "ingressclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["k8s.nginx.org"]
    resources: ["policies", "virtualservers", "virtualserverroutes", "transportservers"]
    verbs: ["get", "list", "watch"]