apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nginx-ingress-controller
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: default
roleRef:
  kind: ClusterRole
  name: nginx-ingress-controller
  apiGroup: rbac.authorization.k8s.io