apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes  1;

    events {
        worker_connections  1024;
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;

        error_log syslog:server=unix:/var/lib/nginx/nginx-syslog.sock debug;
        access_log syslog:server=unix:/var/lib/nginx/nginx-syslog.sock combined;

        server {
            listen 8080;

            location /stub_status {
                stub_status;
                allow 127.0.0.1;
                allow 10.0.0.0/8;
                deny all;
            }

            location / {
                root /usr/share/nginx/html;
                index index.html;
            }
        }
    }
