apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/enable-debug: "true"
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
  {{- range .Values.ingressRules }}
  - host: {{ .host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .serviceName }}
            port:
              number: {{ .servicePort }}
  {{- end }}
