{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: {{ .Release.Name }}
{{- end }}
